#!/usr/bin/env python3
"""Wiki-verified EQL spell lists, per class.

The spell FILE ships ~74k entries inherited from Live EverQuest, but only a
fraction are actually obtainable on EQL's L1-50 server. The EQL Spell
Explorer project (github.com/Amerzel/eql-info) maintains hand-verified
per-class lists (its `verified/*.txt`, cross-checked against eqlwiki.com):
every spell below was confirmed obtainable in-game at the level shown.

GENERATED data -- regenerate by re-running the fetch snippet in the commit
that produced it (source: eql-info `verified/<class>.txt`, HEAD of
2026-07-11). Classes with no verified list (Warrior/Monk/Berserker
-- no spell casters) simply aren't present; callers must treat a missing
class as "no data" rather than "nothing verified".

Names are stored exactly as the game spells them; use verified_levels()
for a lowercased lookup table.
"""

VERIFIED_SPELLS = {
    'Bard': {
        'Chant of Battle': 1,
        'Chords of Dissonance': 2,
        "Jaxan's Jig o` Vigor": 3,
        "Selo's Accelerando": 5,
        'Hymn of Restoration': 6,
        "Jonthan's Whistling Warsong": 7,
        "Kelin's Lugubrious Lament": 8,
        'Elemental Rhythms': 9,
        'Magical Monologue': 9,
        'Anthem de Arms': 10,
        "Cinda's Charismatic Carillon": 11,
        "Brusco's Boastful Bellow": 12,
        'Purifying Rhythms': 13,
        "Kelin's Lucid Lullaby": 15,
        'Song of Sustenance': 15,
        "Tarew's Aquatic Ayre": 16,
        'Guardian Rhythms': 17,
        "Denon's Disruptive Discord": 18,
        "Shauri's Sonorous Clouding": 19,
        "Cassindra's Chant of Clarity": 20,
        "Largo's Melodic Binding": 20,
        "Melanie's Mellifluous Motion": 21,
        "Alenia's Disenchanting Melody": 22,
        "Selo's Consonant Chain": 23,
        "Lyssa's Veracious Concord": 24,
        'Psalm of Warmth': 25,
        "Angstlich's Appalling Screech": 26,
        "Solon's Song of the Sirens": 27,
        "Crission's Pixie Strike": 28,
        'Psalm of Vitality': 29,
        'Amplification': 30,
        "Fufil's Curtailing Chant": 30,
        "Agilmente's Aria of Eagles": 31,
        "Cassindra's Chorus of Clarity": 32,
        'Psalm of Cooling': 33,
        'Cantata of Soothing': 34,
        "Lyssa's Solidarity of Vision": 34,
        "Denon's Dissension": 35,
        "Vilia's Verses of Celerity": 36,
        'Psalm of Purity': 37,
        "Tuyen's Chant of Flame": 38,
        "Katta's Song of Sword Dancing": 39,
        "Solon's Bewitching Bravura": 39,
        "Sionachie's Dreams": 40,
        "Syvelian's Anti-Magic Aria": 40,
        'Psalm of Mystic Shielding': 41,
        "McVaxius' Berserker Crescendo": 42,
        "Tuyen's Chant of Disease": 42,
        "Denon's Desperate Dirge": 43,
        "Cassindra's Elegy": 44,
        'Aria of Asceticism': 45,
        "Jonthan's Provocation": 45,
        "Rizlona's Embers": 45,
        "Tuyen's Chant of Frost": 46,
        "Niv's Melody of Preservation": 47,
        "Selo's Chords of Cessation": 48,
        "Selo's Accelerating Chorus": 49,
        'Shield of Songs': 49,
        'Melody of Ervaj': 50,
        "Tuyen's Chant of Poison": 50,
        'Verses of Victory': 50,
    },
    'Beastlord': {
        'Minor Healing': 1,
        'Wild Spirit': 1,
        'Sense Animals': 2,
        'Endure Cold': 3,
        'Cure Disease': 4,
        'Tame Spirit': 4,
        'Flash of Light': 5,
        'Inner Fire': 7,
        'Spirit of Sharik': 8,
        'Endure Fire': 9,
        "Sharik's Replenishing": 9,
        'Scale Skin': 10,
        'Fleeting Fury': 11,
        'Blast of Frost': 12,
        'Cure Poison': 13,
        'Spirit of Lightning': 13,
        'Light Healing': 14,
        'Sicken': 14,
        'Strengthen': 14,
        "Keshuval's Rejuvenation": 15,
        'Spirit of Khaliz': 15,
        'Serpent Sight': 16,
        'Spirit of Bear': 17,
        'Summon Drink': 17,
        'Endure Poison': 18,
        'Spirit of the Blizzard': 18,
        'Tainted Breath': 19,
        'Tiny Companion': 19,
        'Drowsy': 20,
        'Spirit of Keshuval': 21,
        'Endure Disease': 22,
        'Frost Dagger': 23,
        'Shrink': 23,
        'Healing': 24,
        'Spirit of Wolf': 24,
        'Enduring Breath': 25,
        'Spirit Strike': 26,
        'Turtle Skin': 26,
        "Herikol's Soothing": 27,
        'Spirit Strength': 28,
        'Spirit of Inferno': 28,
        'Spirit Sight': 29,
        'Summon Food': 29,
        'Spirit of Herikol': 30,
        'Summon Companion': 31,
        'Levitate': 32,
        'Ice Spear': 33,
        'Endure Magic': 34,
        'Greater Healing': 34,
        'Cancel Magic': 35,
        'Envenomed Breath': 35,
        "Yekan's Recovery": 36,
        'Spirit of Ox': 37,
        "Yekan's Quickening": 37,
        'Spirit of Monkey': 38,
        'Spirit of the Scorpion': 38,
        'Spirit of Yekan': 39,
        'Spirit of the Shrew': 39,
        'Malaria': 40,
        'Raging Strength': 41,
        'Spiritual Light': 41,
        'Spiritual Brawn': 42,
        'Invisibility': 43,
        'Listless Power': 44,
        'Pack Shrew': 44,
        'Counteract Disease': 45,
        'Spirit of Kashek': 46,
        'Spirit of Vermin': 46,
        'Frenzy': 47,
        'Frost Shard': 47,
        'Protect': 48,
        'Spirit Salve': 48,
        'Vigor of Zehkes': 49,
        'Ward of Calliav': 49,
        "Sha's Lethargy": 50,
    },
    'Cleric': {
        'Courage': 1,
        'Cure Poison': 1,
        'Divine Aura': 1,
        'Flash of Light': 1,
        'Holy Armor': 1,
        'Lull': 1,
        'Minor Healing': 1,
        'Spook the Dead': 1,
        'Strike': 1,
        'True North': 1,
        'Yaulp': 1,
        'Reckless Strength': 2,
        'Stun': 2,
        'Cure Blindness': 3,
        'Summon Drink': 3,
        'Cure Disease': 4,
        'Light Healing': 4,
        'Ward Undead': 4,
        'Furor': 5,
        'Gate': 5,
        'Soothe': 5,
        'Endure Poison': 6,
        'Fear': 6,
        'Sanctuary': 6,
        'Center': 7,
        'Hammer of Wrath': 7,
        'Root': 7,
        'Blessing of the Page': 8,
        'Echo of Health': 8,
        'Endure Fire': 8,
        'Remove Minor Curse': 8,
        'Summon Food': 8,
        'Sense the Dead': 9,
        'Word of Pain': 9,
        'Bind Affinity': 10,
        'Healing': 10,
        'Endure Disease': 11,
        'Invisibility Versus Undead': 11,
        'Symbol of Transal': 11,
        'Halo of Light': 12,
        'Reanimation': 12,
        'Sense Summoned': 12,
        'Cancel Magic': 13,
        'Endure Cold': 13,
        'Expulse Undead': 13,
        'Echoing Light': 14,
        'Smite': 14,
        'Blessing of Piety': 15,
        'Calm': 15,
        'Spirit Armor': 15,
        'Blessing of the Squire': 16,
        'Endure Magic': 16,
        'Holy Might': 16,
        'Yaulp II': 16,
        'Daring': 17,
        'Ward Summoned': 17,
        'Reconstitution': 18,
        'Celestial Remedy': 19,
        'Word of Shadow': 19,
        'Greater Healing': 20,
        'Hammer of Striking': 20,
        'Ward of Vie': 20,
        'Inspire Fear': 21,
        'Symbol of Ryltan': 21,
        'Wave of Fear': 21,
        'Bravery': 22,
        'Counteract Poison': 22,
        'Reparation': 22,
        'Dismiss Undead': 23,
        'Remove Lesser Curse': 23,
        'Renewing Echo': 24,
        'Guard': 25,
        'Sermon of the Righteous': 25,
        'Panic the Dead': 26,
        'Word of Spirit': 26,
        'Expulse Summoned': 27,
        'Instill': 27,
        'Revive': 27,
        'Abundant Drink': 28,
        'Counteract Disease': 28,
        'Celestial Health': 29,
        'Divine Barrier': 29,
        'Imbue Amber': 29,
        'Imbue Black Pearl': 29,
        'Imbue Black Sapphire': 29,
        'Imbue Diamond': 29,
        'Imbue Emerald': 29,
        'Imbue Opal': 29,
        'Imbue Peridot': 29,
        'Imbue Plains Pebble': 29,
        'Imbue Rose Quartz': 29,
        'Imbue Ruby': 29,
        'Imbue Sapphire': 29,
        'Imbue Topaz': 29,
        'Mass Imbue Amber': 29,
        'Mass Imbue Black Pearl': 29,
        'Mass Imbue Black Sapphire': 29,
        'Mass Imbue Diamond': 29,
        'Mass Imbue Emerald': 29,
        'Mass Imbue Opal': 29,
        'Mass Imbue Peridot': 29,
        'Mass Imbue Plains Pebble': 29,
        'Mass Imbue Rose Quartz': 29,
        'Mass Imbue Ruby': 29,
        'Mass Imbue Sapphire': 29,
        'Mass Imbue Topaz': 29,
        'Wrath': 29,
        'Resist Poison': 30,
        'Superior Healing': 30,
        'Word of Health': 30,
        'Force': 31,
        'Frenzied Strength': 31,
        'Symbol of Pinzarn': 31,
        'Atone': 32,
        'Renewal': 32,
        'Valor': 32,
        'Abundant Food': 33,
        'Expel Undead': 33,
        'Resist Fire': 33,
        'Armor of Protection': 34,
        'Blessing of the Knight': 34,
        'Blinding Luminance': 34,
        'Celestial Echo': 34,
        'Tremor': 34,
        'Armor of Faith': 35,
        'Blessing of Faith': 35,
        'Invoke Fear': 36,
        'Pacify': 36,
        'Resist Disease': 36,
        'Dismiss Summoned': 37,
        'Resuscitate': 37,
        'Turning of the Unnatural': 37,
        'Nullify Magic': 38,
        'Remove Curse': 38,
        'Resist Cold': 38,
        'Promised Renewal': 39,
        'Sacred Word': 39,
        'Word of Souls': 39,
        'Guard of Vie': 40,
        'Hammer of Requital': 40,
        'Temperance': 40,
        'Symbol of Naltron': 41,
        'Yaulp III': 41,
        'Resolution': 42,
        'Restoration': 42,
        'Banish Undead': 43,
        'Resist Magic': 43,
        'Sacred Echo': 43,
        'Celestial Healing': 44,
        'Earthquake': 44,
        'Retribution': 44,
        'Blessing of Temperance': 45,
        'Healing Light': 45,
        'Shield of Words': 45,
        'Word of Healing': 45,
        'Immobilize': 46,
        'Sound of Force': 46,
        'Expel Summoned': 47,
        'Resurrection': 47,
        'Abolish Poison': 48,
        'Blessing of the Lord Commander': 48,
        'Improved Invisibility to Undead': 48,
        'Armor of the Faithful': 49,
        'Word Divine': 49,
        'Ward of the Divine': 50,
    },
    'Druid': {
        'Burst of Flame': 1,
        'Dance of the Fireflies': 1,
        'Endure Fire': 1,
        'Flame Lick': 1,
        'Lull Animal': 1,
        'Minor Healing': 1,
        'Panic Animal': 1,
        'Sense Animals': 1,
        'Skin like Wood': 1,
        'Snare': 1,
        'Tangling Weeds': 1,
        'Grasping Roots': 2,
        'Ward Summoned': 2,
        'Burst of Fire': 3,
        'Whirling Wind': 3,
        'Budding Heal': 4,
        'Camouflage': 4,
        'Cure Disease': 4,
        'Invoke Lightning': 4,
        'Cure Poison': 5,
        'Gate': 5,
        'Harmony': 5,
        'Enduring Breath': 6,
        'Firefist': 6,
        'Treeform': 6,
        'Shield of Thistles': 7,
        'Strength of Earth': 7,
        'Thistlecoat': 7,
        'Ignite': 8,
        'Invisibility Versus Animals': 8,
        'Remove Minor Curse': 8,
        'Endure Cold': 9,
        'Light Healing': 9,
        'Protection of Wood': 9,
        'Starshine': 9,
        'Spirit of Wolf': 10,
        'Sprouting Heal': 10,
        'Stinging Swarm': 10,
        'Summon Drink': 10,
        'Halo of Light': 11,
        'Summon Food': 11,
        'Bind Affinity': 12,
        'Cascade of Hail': 12,
        'Befriend Animal': 13,
        'Expulse Summoned': 13,
        'See Invisible': 13,
        'Levitate': 14,
        'Skin like Rock': 14,
        'Calm Animal': 15,
        'Ring of North Karana': 15,
        'Ring of Surefall Glade': 15,
        'Terrorize Animal': 15,
        'Careless Lightning': 16,
        'Dizzying Wind': 16,
        'Ring of Butcherblock': 16,
        'Barbcoat': 17,
        'Ring of Toxxulia': 17,
        'Ring of West Commons': 17,
        'Shield of Barbs': 17,
        'Tiny Companion': 17,
        'Cancel Magic': 18,
        'Feral Spirit': 18,
        'Lesser Succor': 18,
        'Superior Camouflage': 18,
        'Endure Disease': 19,
        'Endure Poison': 19,
        'Healing': 19,
        'Protection of Rock': 19,
        'Flowering Heal': 20,
        'Resist Fire': 20,
        'Ring of South Ro': 20,
        'Ring of Stonebrunt': 20,
        'Wolf Form': 20,
        'Ensnaring Roots': 21,
        'Ring of Steamfont': 21,
        'Spirit of Cheetah': 21,
        'Tremor': 21,
        'Pogonip': 22,
        'Ring of Feerrott': 22,
        'Ring of Lavastorm': 22,
        'Sunbeam': 22,
        'Charm Animals': 23,
        'Dismiss Summoned': 23,
        'Remove Lesser Curse': 23,
        'Creeping Crud': 24,
        'Skin like Steel': 24,
        'Circle of Butcherblock': 25,
        'Circle of North Karana': 25,
        'Circle of Toxxulia': 25,
        'Immolate': 25,
        'Ring of Misty Thicket': 25,
        'Circle of Surefall Glade': 26,
        'Ensnare': 26,
        'Scale of Wolf': 26,
        'Succor: East Karana': 26,
        'Bramblecoat': 27,
        'Circle of West Commons': 27,
        'Protection of Steel': 27,
        'Shield of Brambles': 27,
        'Beguile Plants': 28,
        'Circle of Stonebrunt': 28,
        'Combust': 28,
        'Counteract Disease': 28,
        'Counteract Poison': 28,
        'Greater Healing': 29,
        'Harmony of Nature': 29,
        'Imbue Emerald': 29,
        'Imbue Plains Pebble': 29,
        'Mass Imbue Emerald': 29,
        'Mass Imbue Plains Pebble': 29,
        'Blooming Heal': 30,
        'Circle of Lavastorm': 30,
        'Fury of Air': 30,
        'Greater Wolf Form': 30,
        'Resist Cold': 30,
        'Spirit of the Shrew': 30,
        'Circle of Steamfont': 31,
        'Earthquake': 31,
        'Lightning Strike': 31,
        'Circle of Feerrott': 32,
        'Circle of South Ro': 32,
        'Drones of Doom': 32,
        'Succor: Butcherblock': 32,
        'Zephyr: Toxxulia': 32,
        'Beguile Animals': 33,
        'Expel Summoned': 33,
        'Zephyr: Butcherblock': 33,
        'Endure Magic': 34,
        'Healing Water': 34,
        'Regeneration': 34,
        'Strength of Stone': 34,
        'Zephyr: North Karana': 34,
        'Pack Shrew': 35,
        'Pack Spirit': 35,
        'Share Wolf Form': 35,
        'Zephyr: Stonebrunt': 35,
        'Zephyr: Surefall Glade': 35,
        'Zephyr: West Commons': 35,
        'Circle of Misty Thicket': 36,
        'Enveloping Roots': 36,
        'Skin like Diamond': 36,
        'Avalanche': 37,
        'Shield of Spikes': 37,
        'Spikecoat': 37,
        'Firestrike': 38,
        'Remove Curse': 38,
        'Succor: South Ro': 38,
        "Nature's Renewal": 39,
        'Pack Regeneration': 39,
        'Protection of Diamond': 39,
        'Zephyr: Feerrott': 39,
        'Zephyr: Steamfont': 39,
        'Blossoming Heal': 40,
        'Drifting Death': 40,
        'Form of the Great Wolf': 40,
        'Zephyr: South Ro': 40,
        'Savage Spirit': 41,
        'Succor: Lavastorm': 41,
        'Summon Companion': 41,
        'Chloroplast': 42,
        'Fixation of Ro': 42,
        'Allure of the Wild': 43,
        'Banish Summoned': 43,
        'Dustdevil': 43,
        'Nullify Magic': 43,
        'Resist Disease': 44,
        'Resist Poison': 44,
        'Storm Strength': 44,
        'Superior Healing': 44,
        'Engulfing Roots': 45,
        'Pack Chloroplast': 45,
        'Share Form of the Great Wolf': 45,
        'Zephyr: Misty Thicket': 45,
        'Lightning Blast': 46,
        'Skin like Nature': 46,
        'Succor: North Karana': 46,
        'Ice': 47,
        'Shield of Thorns': 47,
        'Thorncoat': 47,
        'Zephyr: Lavastorm': 47,
        'Efflorescing Heal': 48,
        'Fire': 48,
        'Improved Superior Camouflage': 48,
        'Starfire': 48,
        'Upheaval': 48,
        "Forest's Renewal": 49,
        'Legacy of Spike': 49,
        'Protection of Nature': 49,
        'Resist Magic': 49,
        'Vengeance of the Wild': 49,
        'Everlasting Breath': 50,
        'Levitation': 50,
    },
    'Enchanter': {
        'Lull': 1,
        'Minor Illusion': 1,
        'Minor Shielding': 1,
        "Pendril's Animation": 1,
        'Reclaim Energy': 1,
        'Shallow Breath': 1,
        'Strengthen': 1,
        'Taper Enchantment': 1,
        'True North': 1,
        'Weaken': 1,
        'Illusion: Human': 2,
        "Juli's Animation": 2,
        'Mesmerize': 2,
        'Tashina': 2,
        'Color Flux': 3,
        'Fear': 3,
        'Haze': 3,
        'Illusion: Half-Elf': 3,
        'Enfeeblement': 4,
        'Gate': 4,
        'Invisibility': 4,
        'Suffocating Sphere': 4,
        'Eye of Confusion': 5,
        'Illusion: Wood Elf': 5,
        'Sentinel': 5,
        'Lesser Shielding': 6,
        'Root': 6,
        'See Invisible': 6,
        'Soothe': 6,
        'Cancel Magic': 7,
        'Chaotic Feedback': 7,
        'Enchant Clay': 7,
        'Enchant Silver': 7,
        'Mass Enchant Silver': 7,
        "Mircyl's Animation": 7,
        'Alliance': 8,
        'Bind Sight': 8,
        'Illusion: Gnome': 8,
        'Mass Enchant Clay': 8,
        'Ebbing Strength': 9,
        "Kilan's Animation": 9,
        'Languid Pace': 9,
        'Whirl Till You Hurl': 9,
        'Illusion: Dark Elf': 10,
        'Memory Blur': 10,
        'Mist': 10,
        'Serpent Sight': 10,
        'Charm': 11,
        'Choke': 11,
        'Illusion: High Elf': 11,
        'Intellectual Advancement': 11,
        'Mass Thicken Mana': 11,
        'Thicken Mana': 11,
        'Bind Affinity': 12,
        'Enduring Breath': 12,
        'Illusion: Erudite': 12,
        'Illusion: Halfling': 12,
        'Enthrall': 13,
        'Illusion: Dwarf': 13,
        'Rune I': 13,
        'Breeze': 14,
        'Enchant Electrum': 14,
        'Invisibility Versus Undead': 14,
        'Mass Enchant Electrum': 14,
        "Shalee's Animation": 14,
        'Illusion: Barbarian': 15,
        'Illusion: Tree': 15,
        'Levitate': 15,
        'Quickness': 15,
        'Chase the Moon': 16,
        'Disempower': 16,
        'Mesmerization': 16,
        'Sanity Warp': 16,
        'Shielding': 16,
        'Cloud': 17,
        'Endure Magic': 17,
        'Illusion: Ogre': 17,
        'Intellectual Superiority': 17,
        "Sisna's Animation": 17,
        'Calm': 18,
        'Illusion: Troll': 18,
        'Sympathetic Aura': 18,
        'Tashani': 18,
        'Berserker Strength': 19,
        'Crystallize Mana': 19,
        'Feckless Might': 19,
        'Tiny Companion': 19,
        'Benevolence': 20,
        'Color Shift': 20,
        'Illusion: Iksar': 20,
        'Mass Crystallize Mana': 20,
        'Shifting Sight': 20,
        'Alacrity': 21,
        'Chaos Flux': 21,
        'Illusion: Earth Elemental': 21,
        'Rune II': 22,
        "Sagar's Animation": 22,
        'Strip Enchantment': 22,
        'Beguile': 23,
        'Major Shielding': 23,
        'Tepid Deeds': 23,
        'Enchant Gold': 24,
        'Illusion: Skeleton': 24,
        'Mass Enchant Gold': 24,
        'Feedback': 25,
        'Instill': 25,
        'Listless Power': 25,
        'Clarity': 26,
        'Curse of the Simple Mind': 26,
        'Haunting Visage': 26,
        'Suffocate': 26,
        'Clarify Mana': 27,
        'Obscure': 27,
        'Ultravision': 27,
        'Augmentation': 28,
        "Dyn's Dizzying Draught": 28,
        'Illusion: Water Elemental': 28,
        'Nullify Magic': 28,
        'Illusion: Air Elemental': 29,
        'Mass Clarify Mana': 29,
        "Uleen's Animation": 29,
        'Ward of Alendar': 29,
        'Entrance': 30,
        'Entrancing Lights': 30,
        'Mana Sieve': 30,
        "Boltran's Animation": 31,
        'Greater Shielding': 31,
        'Radiant Visage': 31,
        'Anarchy': 32,
        'Cast Sight': 32,
        'Enchant Platinum': 32,
        'Mass Enchant Platinum': 32,
        'Illusion: Fire Elemental': 33,
        'Rune III': 33,
        'Gift of Magic': 34,
        'Insipid Weakness': 34,
        'Insight': 35,
        'Invoke Fear': 35,
        'Pacify': 35,
        'Calming Visage': 36,
        'Gravity Flux': 36,
        'Mind Wipe': 36,
        "Aanya's Animation": 37,
        'Cajoling Whispers': 37,
        'Illusion: Dry Bone': 37,
        'Resist Magic': 37,
        'Shade': 37,
        'Distill Mana': 38,
        'Illusion: Spirit Wolf': 38,
        'Rampage': 38,
        'Wandering Mind': 38,
        'Celerity': 39,
        'Immobilize': 39,
        'Mass Distill Mana': 39,
        'Arch Shielding': 40,
        'Boon of the Garou': 40,
        'Incapacitate': 40,
        'Rune IV': 40,
        'Brilliance': 41,
        'Shiftless Deeds': 41,
        'Tashania': 41,
        "Yegoreff's Animation": 41,
        'Boon of the Clear Mind': 42,
        'Illusion: Werewolf': 42,
        'Pillage Enchantment': 42,
        'Weakness': 42,
        'Bounce': 43,
        'Color Skew': 43,
        'Discordant Mind': 43,
        'Summon Companion': 43,
        'Guard of Alendar': 44,
        'Illusion: Scaled Wolf': 44,
        'Leviathan Eyes': 44,
        'Illusion: Imp': 45,
        'Paralyzing Earth': 45,
        'Purify Mana': 45,
        'Reoccurring Amnesia': 45,
        'Adorning Grace': 46,
        'Allure': 46,
        'Blanket of Forgetfulness': 46,
        'Berserker Spirit': 47,
        'Dazzle': 47,
        'Gasping Embrace': 47,
        'Mass Purify Mana': 47,
        'Swift Like the Wind': 47,
        'Group Resist Magic': 48,
        "Kintaz's Animation": 48,
        'Shadow': 48,
        'Collaboration': 50,
        'Improved Invisibility': 50,
        'Theft of Thought': 50,
    },
    'Magician': {
        'Burst of Flame': 1,
        'Fire Flux': 1,
        'Flare': 1,
        'Minor Shielding': 1,
        'Reclaim Energy': 1,
        'Summon Dagger': 1,
        'Summon Drink': 1,
        'Summon Food': 1,
        'True North': 1,
        'Elementalkin: Water': 2,
        'Summon Bandages': 2,
        'Summon Brass Choker': 2,
        'Elementalkin: Fire': 3,
        'Sense Summoned': 3,
        'Summon Wisp': 3,
        'Burn': 4,
        'Elementalkin: Air': 4,
        'Gate': 4,
        'Elementalkin: Earth': 5,
        'Flame Bolt': 5,
        'Lesser Shielding': 5,
        'Elementaling: Water': 6,
        'Eye of Zomm': 6,
        'Elementaling: Fire': 7,
        'Renew Elements': 7,
        'Shield of Fire': 7,
        'Shock of Blades': 7,
        'Elementaling: Air': 8,
        'Invisibility': 8,
        'Staff of Tracing': 8,
        'Summon Linen Mantle': 8,
        'Elementaling: Earth': 9,
        'Summon Fang': 9,
        'Ward Summoned': 9,
        'Cancel Magic': 10,
        'Elemental: Water': 10,
        'Rain of Blades': 10,
        'Summon Tarnished Bauble': 10,
        'Burnout': 11,
        'Elemental: Fire': 11,
        'Summon Elemental Defender': 11,
        'Bind Affinity': 12,
        'Column of Fire': 12,
        'Elemental: Air': 12,
        'Elemental: Earth': 13,
        'Phantom Leather': 13,
        'Minor Summoning: Water': 14,
        'Staff of Warding': 14,
        'Minor Summoning: Fire': 15,
        'Shock of Flame': 15,
        'Summon Heatstone': 15,
        'Summon Throwing Dagger': 15,
        'Minor Summoning: Air': 16,
        'See Invisible': 16,
        'Shielding': 16,
        'Summon Tiny Ring': 16,
        'Minor Summoning: Earth': 17,
        'Rain of Fire': 17,
        'Summon Phantom Leather': 17,
        'Summon Waterstone': 17,
        'Bolt of Flame': 18,
        'Expulse Summoned': 18,
        'Lesser Summoning: Water': 18,
        'Renew Summoning': 18,
        'Elemental Shield': 19,
        'Lesser Summoning: Fire': 19,
        'Shield of Flame': 19,
        'Tiny Companion': 19,
        'Lesser Summoning: Air': 20,
        'Spear of Warding': 20,
        'Summon Arrows': 20,
        'Summon Jade Bracelet': 20,
        'Summon Wooden Bracelet': 20,
        'Cornucopia': 21,
        'Lesser Summoning: Earth': 21,
        'Summon Silver Choker': 21,
        'Everfount': 22,
        'Flame Flux': 22,
        'Malaise': 22,
        'Summoning: Water': 22,
        'Shock of Spikes': 23,
        'Summoning: Fire': 23,
        'Major Shielding': 24,
        'Staff of Runes': 24,
        'Summoning: Air': 24,
        'Dismiss Summoned': 25,
        'Phantom Chain': 25,
        'Summon Phantom Chain': 25,
        'Summoning: Earth': 25,
        'Greater Summoning: Water': 26,
        'Rain of Spikes': 26,
        'Sword of Runes': 26,
        'Expedience': 27,
        'Greater Summoning: Fire': 27,
        'Summon Leather Mantle': 27,
        'Expel Summoned': 28,
        'Greater Summoning: Air': 28,
        'Inferno Shield': 28,
        'Burnout II': 29,
        'Greater Summoning: Earth': 29,
        'Summon Coldstone': 29,
        'Dimensional Hole': 30,
        'Monster Summoning I': 30,
        'Summon Shiny Bauble': 30,
        'Blaze': 31,
        'Minor Conjuration: Water': 31,
        'Summon Shard of the Core': 31,
        'Greater Shielding': 32,
        'Minor Conjuration: Fire': 32,
        'Nullify Magic': 32,
        'Cinder Bolt': 33,
        'Minor Conjuration: Air': 33,
        'Staff of Symbols': 33,
        'Minor Conjuration: Earth': 34,
        'Refresh Summoning': 34,
        'Dagger of Symbols': 35,
        'Rain of Lava': 35,
        'Lesser Conjuration: Water': 36,
        'Summon Companion': 36,
        'Lesser Conjuration: Fire': 37,
        'Summon Ring of Flight': 37,
        'Summon Twisted Ring': 37,
        'Barrier of Combustion': 38,
        'Lesser Conjuration: Air': 38,
        'Summon Phantom Plate': 38,
        'Flame Arc': 39,
        'Lesser Conjuration: Earth': 39,
        'Conjuration: Water': 41,
        'Elemental Armor': 41,
        'Phantom Plate': 41,
        'Shock of Swords': 41,
        'Bounce': 42,
        'Conjuration: Fire': 42,
        'Summon Opal Bracelet': 42,
        'Summon: Orb of Exploration': 42,
        'Arch Shielding': 43,
        'Conjuration: Air': 43,
        'Elemental Maelstrom': 43,
        'Conjuration: Earth': 44,
        'Malaisement': 44,
        'Modulating Rod': 44,
        'Primal Remedy': 44,
        'Summon Stone Bracelet': 44,
        'Shield of Lava': 45,
        'Summon Orb': 45,
        'Greater Conjuration: Earth': 46,
        'Ward of Calliav': 46,
        'Burnout III': 47,
        'Greater Conjuration: Fire': 47,
        'Lava Bolt': 47,
        'Banish Summoned': 48,
        'Greater Conjuration: Air': 48,
        'Summon Elemental Blanket': 48,
        'Greater Conjuration: Water': 49,
        'Rain of Swords': 49,
        'Monster Summoning II': 50,
        'Summon Golden Choker': 50,
    },
    'Necromancer': {
        'Cavorting Bones': 1,
        'Coldlight': 1,
        'Disease Cloud': 1,
        'Invisibility Versus Undead': 1,
        'Lifetap': 1,
        'Minor Shielding': 1,
        'Reclaim Energy': 1,
        'Sense the Dead': 1,
        'Siphon Strength': 1,
        'Fear': 2,
        'Numb the Dead': 2,
        'True North': 2,
        'Endure Cold': 3,
        'Grim Aura': 3,
        'Lifespike': 3,
        'Clinging Darkness': 4,
        'Gate': 4,
        'Leering Corpse': 4,
        'Poison Bolt': 4,
        'Deadeye': 5,
        'Shadow Step': 5,
        'Dark Empathy': 6,
        'Dark Pact': 6,
        'Ward Undead': 6,
        'Gather Shadows': 7,
        'Mend Bones': 7,
        'Vampiric Embrace': 7,
        'Bone Walk': 8,
        'Cancelling of Life': 8,
        'Impart Strength': 8,
        'Lesser Shielding': 8,
        'Leech': 9,
        'Sight Graft': 9,
        'Wave of Enfeeblement': 9,
        'Heat Blood': 10,
        'Scent of Dusk': 10,
        'Spook the Dead': 10,
        'Endure Disease': 11,
        'Engulfing Darkness': 11,
        'Focus Death': 11,
        'Bind Affinity': 12,
        'Convoke Shadow': 12,
        'Lifedraw': 12,
        'Cure Disease': 13,
        'Heart Flutter': 13,
        'Shieldskin': 14,
        'Banshee Aura': 15,
        'Cancel Magic': 15,
        'Infectious Cloud': 15,
        'Voice Graft': 15,
        'Feign Death': 16,
        'Form of Chilled Bone': 16,
        'Hungry Earth': 16,
        'Restless Bones': 16,
        'Shielding': 16,
        'Spirit Armor': 16,
        'Shackle of Bone': 17,
        'Shadow Compact': 17,
        'Allure of Death': 18,
        'Dominate Undead': 18,
        'Negation of Life': 18,
        'Expulse Undead': 19,
        'Shadow Vortex': 19,
        'Tiny Companion': 19,
        'Animate Dead': 20,
        'Harmshield': 20,
        'Siphon Life': 20,
        'Word of Shadow': 20,
        'Breath of the Dead': 21,
        'Rapacious Subvention': 21,
        'Scent of Shadow': 21,
        'Shock of Poison': 21,
        'Leatherskin': 22,
        'Screaming Terror': 22,
        'Shadow Sight': 22,
        'Intensify Death': 23,
        'Rest the Dead': 23,
        'Haunting Corpse': 24,
        'Major Shielding': 24,
        'Resist Cold': 24,
        'Panic the Dead': 25,
        'Renew Bones': 26,
        'Spirit Tap': 26,
        'Dooming Darkness': 27,
        'Eternities Torment': 27,
        'Word of Spirit': 27,
        'Boil Blood': 28,
        'Dismiss Undead': 28,
        'Summon Dead': 29,
        'Vampiric Curse': 29,
        'Invoke Fear': 30,
        'Beguile Undead': 31,
        'Call of Bones': 31,
        'Resist Disease': 31,
        'Steelskin': 32,
        'Surge of Enfeeblement': 32,
        "Torbas' Acid Blast": 32,
        'Greater Shielding': 33,
        'Invoke Shadow': 33,
        'Root': 34,
        'Venom of the Snake': 34,
        'Augment Death': 35,
        'Scourge': 35,
        'Chilling Embrace': 36,
        'Counteract Disease': 36,
        'Word of Souls': 36,
        'Cessation of Life': 37,
        'Nullify Magic': 37,
        'Scent of Darkness': 37,
        'Expel Undead': 38,
        'Shackle of Spirit': 38,
        'Dark Soul': 39,
        'Drain Spirit': 39,
        'Malignant Dead': 39,
        'Asystole': 40,
        'Summon Companion': 40,
        'Arch Shielding': 41,
        'Dead Man Floating': 41,
        'Ignite Bones': 42,
        'Incinerate Bones': 42,
        'Corporeal Empathy': 43,
        'Covetous Subversion': 43,
        'Diamondskin': 43,
        'Bounce': 44,
        'Cackling Bones': 44,
        'Form of Bleached Bone': 44,
        'Pact of Shadow': 44,
        'Auspice': 45,
        'Dead Men Floating': 45,
        'Banish Undead': 46,
        'Insidious Retrogression': 46,
        'Paralyzing Earth': 46,
        'Cajole Undead': 47,
        'Cascading Darkness': 47,
        'Ignite Blood': 47,
        'Drain Soul': 48,
        'Invoke Death': 48,
        'Lich': 48,
        'Bond of Death': 49,
        "Torbas' Poison Blast": 49,
        'Ward of Calliav': 49,
        'Envenomed Bolt': 50,
        'Improved Invisibility to Undead': 50,
    },
    'Paladin': {
        'Minor Healing': 1,
        'Strike': 1,
        'Ward Undead': 1,
        'Flash of Light': 2,
        'True North': 3,
        'Sense the Dead': 4,
        'Cure Poison': 5,
        'Cease': 7,
        'Courage': 8,
        'Furor': 8,
        'Spook the Dead': 9,
        'Yaulp': 9,
        'Light Healing': 10,
        'Lull': 10,
        'Cure Disease': 11,
        'Desist': 13,
        'Hammer of Wrath': 14,
        'Holy Armor': 15,
        'Instrument of Nife': 15,
        'Halo of Light': 16,
        'Invisibility Versus Undead': 17,
        'Reckless Strength': 18,
        'Remove Minor Curse': 19,
        'Root': 19,
        'Smite': 19,
        'Center': 20,
        'Healing': 20,
        'Endure Poison': 21,
        'Reanimation': 22,
        'Hammer of Striking': 23,
        'Symbol of Transal': 24,
        'Soothe': 25,
        'Stun': 28,
        'Endure Magic': 29,
        'Expulse Undead': 30,
        'Greater Healing': 30,
        'Reconstitution': 30,
        'Spirit Armor': 30,
        'Reparation': 31,
        'Cancel Magic': 32,
        'Symbol of Ryltan': 33,
        'Counteract Poison': 34,
        'Remove Lesser Curse': 34,
        'Wrath': 34,
        'Divine Vigor': 35,
        'Daring': 37,
        'Divine Purpose': 37,
        'Endure Disease': 38,
        'Yaulp II': 38,
        'Guard': 39,
        'Revive': 39,
        'Wave of Life': 39,
        'Holy Might': 42,
        'Calm': 43,
        'Ethereal Cleansing': 44,
        'Valor of Marr': 44,
        'Divine Might': 45,
        'Remove Curse': 45,
        'Dismiss Undead': 46,
        'Superior Healing': 46,
        'Symbol of Pinzarn': 46,
        'Thunder of Karana': 47,
        'Valor': 47,
        'Armor of Faith': 48,
        'Divine Aura': 48,
        "Brell's Steadfast Aegis": 49,
        'Pacify': 49,
        'Renewal': 49,
        'Retribution': 49,
        'Flame of Light': 50,
        'Resist Disease': 50,
    },
    'Ranger': {
        'Minor Healing': 1,
        'Glimpse': 2,
        'Flame Lick': 3,
        'Lull Animal': 4,
        'Tangling Weeds': 5,
        'Snare': 6,
        'Skin like Wood': 7,
        'Endure Fire': 9,
        'Dance of the Fireflies': 10,
        'Hawk Eye': 11,
        'Feet like Cat': 12,
        'Cure Poison': 13,
        'Thistlecoat': 13,
        'Burst of Fire': 14,
        'Camouflage': 14,
        'Grasping Roots': 15,
        'Invoke Lightning': 15,
        'Searing Arrow': 15,
        'Light Healing': 16,
        'Panic Animal': 16,
        'Ward Summoned': 16,
        'Bind Sight': 17,
        'Firefist': 17,
        'Endure Cold': 18,
        'Ignite': 19,
        'Enduring Breath': 20,
        'Skin like Rock': 21,
        'Cure Disease': 22,
        'Harmony': 22,
        'Shield of Thistles': 24,
        'Stinging Swarm': 25,
        'Flaming Arrow': 26,
        'Strength of Earth': 26,
        'Eyes of the Cat': 27,
        'Healing': 28,
        'Spirit of Wolf': 28,
        "Riftwind's Protection": 29,
        'Barbcoat': 30,
        'Cancel Magic': 30,
        'Calm Animal': 31,
        'See Invisible': 32,
        'Dismiss Summoned': 33,
        'Bramblecoat': 34,
        'Levitate': 35,
        'Burning Arrow': 36,
        'Call of Sky': 36,
        'Careless Lightning': 37,
        "Nature's Precision": 37,
        'Greater Healing': 38,
        'Skin like Steel': 38,
        'Harmony of Nature': 39,
        'Swarm of Pain': 40,
        'Spirit of the Shrew': 41,
        'Spikecoat': 42,
        'Shield of Brambles': 43,
        'Immolate': 44,
        'Ensnaring Roots': 45,
        'Resist Fire': 46,
        'Scorching Arrow': 46,
        'Superior Camouflage': 47,
        'Call of Earth': 48,
        'Wolf Form': 48,
        'Call of Flame': 49,
        'Pack Shrew': 49,
        'Force of Nature': 50,
        'Jolt': 50,
    },
    'Rogue': {
        'Concussive Poison': 7,
        'Clumsiness Poison': 18,
        'Fettering Poison': 23,
        'Binding Poison': 25,
        'Neurotoxic Poison': 28,
        'Thought Drain Poison': 33,
        'Antimagic Poison': 36,
        'Mage Bane Poison': 39,
        'Paralytic Poison': 42,
    },
    'ShadowKnight': {
        'Lifetap': 1,
        'Spike of Disease': 1,
        'Sense the Dead': 2,
        'Invisibility Versus Undead': 4,
        'Disease Cloud': 5,
        'Siphon Strength': 6,
        'Leering Corpse': 7,
        'Lifespike': 8,
        'Despair': 9,
        'Numb the Dead': 9,
        'Endure Cold': 10,
        'Clinging Darkness': 11,
        'Fear': 12,
        'Shadow Step': 13,
        'Bone Walk': 14,
        'Lifedraw': 15,
        'Scream of Hate': 15,
        'Vampiric Embrace': 15,
        'Grim Aura': 16,
        'Deadeye': 17,
        'Cancelling of Life': 18,
        'Ward Undead': 18,
        'Cure Disease': 19,
        'Tiny Companion': 19,
        'Engulfing Darkness': 20,
        'Spook the Dead': 20,
        'Dark Empathy': 21,
        'Convoke Shadow': 22,
        'Scream of Pain': 23,
        'Feign Death': 24,
        'Endure Disease': 26,
        'Wave of Enfeeblement': 27,
        'Heat Blood': 28,
        'Strengthen Death': 29,
        'Gather Shadows': 30,
        'Restless Bones': 30,
        'Siphon Life': 30,
        'Negation of Life': 31,
        'Shieldskin': 31,
        'Dark Temptation': 32,
        'Terror of Darkness': 33,
        'Spear of Disease': 34,
        'Resist Cold': 35,
        'Shroud of Hate': 35,
        'Cancel Magic': 36,
        'Heart Flutter': 36,
        'Spirit Tap': 36,
        'Scream of Death': 37,
        'Shadow Vortex': 37,
        'Animate Dead': 38,
        'Expulse Undead': 39,
        'Voice of Darkness': 39,
        'Shadow Sight': 40,
        'Blood of Pain': 41,
        'Terror of Shadows': 42,
        'Invoke Fear': 43,
        'Dooming Darkness': 44,
        'Breath of the Dead': 45,
        'Word of Spirit': 45,
        'Summon Dead': 46,
        'Voice of Shadows': 46,
        'Life Leech': 47,
        'Scythe of Darkness': 47,
        'Spear of Pain': 48,
        'Dismiss Undead': 49,
        'Drain Spirit': 49,
        'Harmshield': 50,
        'Shroud of Pain': 50,
    },
    'Shaman': {
        'Burst of Flame': 1,
        'Cure Disease': 1,
        'Dexterous Aura': 1,
        'Endure Cold': 1,
        'Flash of Light': 1,
        'Inner Fire': 1,
        'Minor Healing': 1,
        'Strengthen': 1,
        'True North': 1,
        'Cure Poison': 2,
        'Spirit Pouch': 2,
        'Summon Drink': 2,
        'Feet like Cat': 3,
        'Scale Skin': 3,
        'Fleeting Fury': 4,
        'Frost Rift': 4,
        'Sicken': 4,
        'Drowsy': 5,
        'Endure Fire': 5,
        'Gate': 5,
        'Serpent Sight': 6,
        'Spirit of Bear': 6,
        'Summon Food': 6,
        'Cure Blindness': 7,
        'Sense Animals': 7,
        'Spirit Sight': 7,
        'Endure Disease': 8,
        'Tainted Breath': 8,
        'Talisman of the Beast': 8,
        'Light Healing': 9,
        'Remove Minor Curse': 9,
        'Spirit of Wolf': 9,
        'Invisibility Versus Animals': 10,
        'Levitate': 10,
        'Spirit of Snake': 10,
        'Burst of Strength': 11,
        'Endure Poison': 11,
        'Turtle Skin': 11,
        'Disempower': 12,
        'Enduring Breath': 12,
        'Root': 12,
        'Walking Sleep': 13,
        'Bind Affinity': 14,
        'Snails Healing': 14,
        'Spirit Strike': 14,
        'Infectious Cloud': 15,
        'Shrink': 15,
        'Frenzy': 16,
        'Grow': 16,
        'Impassivity': 16,
        'Tiny Companion': 16,
        'Insidious Fever': 17,
        'Vision': 17,
        'Malaise': 18,
        'Spirit Strength': 18,
        'Spirit of Cat': 18,
        'Affliction': 19,
        'Cancel Magic': 19,
        'Endure Magic': 19,
        'Healing': 19,
        'Creeping Vision': 20,
        'Protect': 20,
        'Spirit of Cheetah': 21,
        'Spirit of Monkey': 21,
        'Spirit of Ox': 21,
        'Counteract Disease': 22,
        'Poison Storm': 22,
        'Scale of Wolf': 22,
        'Cannibalize': 23,
        'Frost Strike': 23,
        'Regeneration': 23,
        'Envenomed Breath': 24,
        'Remove Lesser Curse': 24,
        'Resist Cold': 24,
        'Befriend Animal': 25,
        'Form of the Bear': 25,
        'Rising Dexterity': 25,
        'Counteract Poison': 26,
        'Quickness': 26,
        'Ultravision': 26,
        'Invisibility': 27,
        'Resist Fire': 27,
        "Tagar's Insects": 27,
        'Alluring Aura': 28,
        'Raging Strength': 28,
        'Tortoises Healing': 28,
        'Greater Healing': 29,
        'Imbue Amber': 29,
        'Imbue Diamond': 29,
        'Imbue Ivory': 29,
        'Imbue Jade': 29,
        'Imbue Sapphire': 29,
        'Listless Power': 29,
        'Mass Imbue Amber': 29,
        'Mass Imbue Diamond': 29,
        'Mass Imbue Ivory': 29,
        'Mass Imbue Jade': 29,
        'Mass Imbue Sapphire': 29,
        'Spirit of the Shrew': 29,
        'Fury': 30,
        'Health': 30,
        'Nonchalance': 30,
        'Resist Disease': 30,
        'Nimble': 31,
        'Scourge': 31,
        'Shifting Shield': 31,
        'Charm Animals': 32,
        'Companion Spirit': 32,
        'Malaisement': 32,
        'Talisman of Tnarg': 32,
        'Instill': 33,
        "Winter's Roar": 33,
        'Curse': 34,
        'Pack Shrew': 34,
        'Shock of the Tainted': 34,
        'Resist Poison': 35,
        'Tumultuous Strength': 35,
        'Assiduous Vision': 36,
        'Gale of Poison': 36,
        'Spirit of Bih`Li': 36,
        'Glamour': 37,
        'Venom of the Snake': 37,
        'Vigilant Spirit': 37,
        'Cannibalize II': 38,
        'Insidious Malady': 38,
        'Remove Curse': 38,
        "Togor's Insects": 38,
        'Blinding Luminance': 39,
        'Chloroplast': 39,
        'Deftness': 39,
        'Furious Strength': 39,
        'Spirit Salve': 40,
        'Summon Companion': 40,
        'Talisman of Altuna': 40,
        'Agility': 41,
        'Guardian Spirit': 41,
        'Incapacitate': 41,
        'Alacrity': 42,
        'Blast of Poison': 42,
        'Guardian': 42,
        'Slugs Healing': 42,
        'Odium': 43,
        'Resist Magic': 43,
        'Stamina': 43,
        'Blizzard Blast': 44,
        'Nullify Magic': 44,
        'Stoicism': 44,
        'Frenzied Spirit': 45,
        'Rage': 45,
        'Superior Healing': 45,
        'Harnessing of Spirit': 46,
        'Strength': 46,
        'Charisma': 47,
        'Shock of Venom': 47,
        'Abolish Disease': 48,
        'Dexterity': 48,
        'Malosi': 48,
        'Envenomed Bolt': 49,
        'Infusion of Spirit': 49,
        'Plague': 49,
        "Kragg's Salve": 50,
        'Spirit Quickening': 50,
        'Spirit of the Puma': 50,
        'Talisman of Jasinth': 50,
    },
    'Wizard': {
        'Blast of Cold': 1,
        'Frost Bolt': 1,
        'Minor Shielding': 1,
        'Numbing Cold': 1,
        'Sphere of Light': 1,
        'True North': 1,
        'Glimpse': 2,
        "O`Keil's Radiation": 2,
        'Fade': 3,
        'Root': 3,
        'Gate': 4,
        'See Invisible': 4,
        'Shock of Fire': 4,
        'Fingers of Fire': 5,
        'Fire Bolt': 5,
        'Icestrike': 6,
        'Lesser Shielding': 6,
        'Sense Summoned': 7,
        'Shadow Step': 7,
        'Column of Frost': 8,
        'Eye of Zomm': 8,
        'Shock of Ice': 8,
        'Halo of Light': 9,
        'Resistant Skin': 9,
        "O`Keil's Embers": 10,
        'Shock of Lightning': 10,
        'Cancel Magic': 11,
        'Gaze': 11,
        'Bind Affinity': 12,
        'Firestorm': 12,
        'Frost Spiral of Al`Kabor': 12,
        'Shieldskin': 13,
        'Project Lightning': 14,
        'Flame Shock': 15,
        'Pillar of Fire': 15,
        'Shielding': 15,
        'Bind Sight': 16,
        'Heat Sight': 16,
        'Invisibility': 16,
        'Lightning Bolt': 16,
        'Force Snap': 17,
        'Instill': 17,
        'Fire Spiral of Al`Kabor': 18,
        "Garrison's Mighty Mana Shock": 18,
        'Lesser Evacuate': 18,
        'North Karana Gate': 18,
        'Sight': 19,
        "Tishan's Clash": 19,
        'Toxxulia Gate': 19,
        'Elemental Shield': 20,
        'Greater Faydark Gate': 20,
        'Leatherskin': 21,
        'Stonebrunt Gate': 21,
        'West Commons Gate': 21,
        'Levitate': 22,
        'Nektulos Gate': 22,
        'North Ro Gate': 22,
        'Cazic Temple Gate': 23,
        'Lightning Storm': 23,
        'Major Shielding': 23,
        'West Karana Gate': 23,
        'Cast Force': 24,
        'Column of Lightning': 24,
        'Frost Shock': 24,
        'Minor Familiar': 25,
        'North Karana Portal': 25,
        "O`Keil's Levity": 25,
        'Yonder': 25,
        'Energy Storm': 26,
        'Evacuate: North Karana': 26,
        'Imbue Fire Opal': 26,
        'Inferno Shock': 26,
        'Bonds of Force': 27,
        'Greater Faydark Portal': 27,
        'Stonebrunt Portal': 27,
        'Mass Imbue Fire Opal': 28,
        'Shock Spiral of Al`Kabor': 28,
        'Thunder Strike': 28,
        'Toxxulia Portal': 28,
        'Magnify': 29,
        'Steelskin': 30,
        'Thunderclap': 30,
        'Circle of Force': 31,
        "O`Keil's Flickering Flame": 31,
        'Evacuate: Greater Faydark': 32,
        'Harvest': 32,
        'Lava Storm': 32,
        'Nektulos Portal': 32,
        'Cazic Temple Portal': 33,
        'Greater Shielding': 33,
        'Ice Shock': 34,
        'Nullify Magic': 34,
        "Elnerick's Entombment of Ice": 35,
        'Force Spiral of Al`Kabor': 35,
        'Translocate: North Karana': 35,
        'Translocate: Stonebrunt': 35,
        'West Commons Portal': 35,
        'North Ro Portal': 36,
        'Translocate: Greater Faydark': 36,
        'Concussion': 37,
        'Lightning Shock': 37,
        "Markar's Relocation": 37,
        'Translocate: Toxxulia': 37,
        'West Karana Portal': 37,
        'Chill Sight': 38,
        'Evacuate: South Ro': 38,
        'Shifting Sight': 38,
        'Immobilize': 39,
        'Invisibility to Undead': 39,
        'Diamondskin': 40,
        'Translocate: West Commons': 40,
        'Vision Shift': 40,
        'Force Strike': 41,
        'Frost Storm': 41,
        'Translocate: Nektulos': 41,
        'Elemental Armor': 42,
        'Evacuate: Nektulos': 42,
        'Greater Mass Imbue Fire Opal': 42,
        'Translocate: West Karana': 42,
        'Conflagration': 43,
        'Gravity Flux': 43,
        'Translocate: North Ro': 43,
        'Arch Shielding': 44,
        'Bounce': 44,
        'Enticement of Flame': 44,
        'Mana Ignition': 44,
        'Translocate: Cazic Temple': 44,
        'Lesser Familiar': 45,
        'Supernova': 45,
        'Alter Plane: Hate': 46,
        'Alter Plane: Sky': 46,
        'Evacuate: West Karana': 47,
        "Markar's Clash": 47,
        'Rend': 47,
        'Paralyzing Earth': 48,
        'Wrath of Al`Kabor': 48,
        'Ice Comet': 49,
        'Ward of Calrena': 49,
        'Levitation': 50,
        'Mana Detonation': 50,
        'Translocate': 50,
    },
}


def verified_levels(class_name):
    """{lowercased spell name: min level} for a class, or None when there
    is NO verified data for that class (distinct from an empty dict)."""
    table = VERIFIED_SPELLS.get(class_name)
    if table is None:
        return None
    return {name.lower(): lvl for name, lvl in table.items()}
